### PR TITLE
fix negative values

### PR DESCRIPTION
**Pull request by adku1173**
### Description

* Uses the `positive` argument in all `LassoLars` solvers to ensure positive results (sourcemaps)
* Adds a line in tests to check for negative values
* Unfortunately, `OrthogonalMatchingPursuitCV` leads to some negative values for the regression test when using `BeamformerDamasPlus` (`OrthogonalMatchingPursuitCV` has no attribute to ensure positivity)

### Reference issue

related to #204 

### Checklist

- [x] I have read the [Contributing](https://www.acoular.org/contributing/index.html) section.
- [x] My branch is up-to-date with the *master* branch of the [Acoular repository](https://github.com/acoular/acoular).
- [x] My changes fulfill the [Code Quality](https://www.acoular.org/contributing/quality.html) standards.
- [x] I have updated the [What's new](https://www.acoular.org/news/index.html) section the the [documentation](https://github.com/acoular/acoular/blob/master/docs/source/news/index.rst) explaining my changes.
- [x] I have appended myself to the [CITATION.cff](https://github.com/acoular/acoular/blob/master/CITATION.cff) file.

### CODE REVIEW

**Review by artpelling — DISMISSED** [review]

**Comment by artpelling** [comment]
@adku1173  tests are currently failing.

**Comment by adku1173** [comment]
@artpelling I am confused. The problem is that the locally resulting source maps are slightly different from the CI source maps, although the algorithm's parametrization and the produced results are plausible. I already tried to pin the scikit-learn version without success. 

We could save the snapshots produced by the CI or expect the tests to fail without being strict, meaning that the snapshot test is allowed both to fail or pass for GIB with LassoLarsCV / LassoLars.

ci
local
diff

**Comment by artpelling** [comment]
> @artpelling I am confused. The problem is that the locally resulting source maps are slightly different from the CI source maps, although the algorithm's parametrization and the produced results are plausible. I already tried to pin the scikit-learn version without success.
> 

Hmm thats really unfortunate. This can only be due to something happening under the hood.

> We could save the snapshots produced by the CI or expect the tests to fail without being strict, meaning that the snapshot test is allowed both to fail or pass for GIB with LassoLarsCV / LassoLars.
> 

Not sure what is best here. Could we maybe raise the tolerance without defeating the purpose of the test? Otherwise, I'd say we should expect it to fail or pass since that is the truth 😅 

@acoular/all Any other ideas?

**Comment by esarradj** [comment]
I think the tests must give the same result (pass/fail) regardless of whether they are executed in the CI or not. Unless we do not find a definitive reason and actual failure, I would opt for relaxing the tolerance. See also this recommendation: https://github.com/scikit-learn/scikit-learn/discussions/27120

One thing that might be the actual reason for this behavior is that CV solvers pick some training data by splitting the available data. Maybe, the splitting process depends somehow on the hardware or the state of the random_number generator. The latter should not be the case, see https://scikit-learn.org/1.5/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold , but who knows.

**Review by artpelling — APPROVED** [review]

**Pull request merged**
